package com.github.seed.core.scalamodel;

public interface ScalaModelKWLexersym {
    public final static int
      Char_DollarSign = 36,
      Char_Percent = 23,
      Char_Minus = 24,
      Char_Colon = 16,
      Char_Equal = 25,
      Char_LessThan = 26,
      Char_GreaterThan = 21,
      Char_Sharp = 27,
      Char_AtSign = 28,
      Char__ = 29,
      Char_a = 3,
      Char_b = 22,
      Char_c = 8,
      Char_d = 10,
      Char_e = 1,
      Char_f = 17,
      Char_g = 30,
      Char_h = 11,
      Char_i = 6,
      Char_j = 31,
      Char_k = 32,
      Char_l = 4,
      Char_m = 18,
      Char_n = 13,
      Char_o = 9,
      Char_p = 14,
      Char_q = 37,
      Char_r = 5,
      Char_s = 7,
      Char_t = 2,
      Char_u = 15,
      Char_v = 19,
      Char_w = 20,
      Char_x = 33,
      Char_y = 12,
      Char_z = 34,
      Char_EOF = 35;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "e",
                 "t",
                 "a",
                 "l",
                 "r",
                 "i",
                 "s",
                 "c",
                 "o",
                 "d",
                 "h",
                 "y",
                 "n",
                 "p",
                 "u",
                 "Colon",
                 "f",
                 "m",
                 "v",
                 "w",
                 "GreaterThan",
                 "b",
                 "Percent",
                 "Minus",
                 "Equal",
                 "LessThan",
                 "Sharp",
                 "AtSign",
                 "_",
                 "g",
                 "j",
                 "k",
                 "x",
                 "z",
                 "EOF",
                 "DollarSign",
                 "q"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
