package com.github.seed.core.scalamodel;

public interface ScalaModelLexerexp {
    public final static int
      IF = 1,
      FOR = 2,
      ELSE = 3,
      THIS = 4,
      NULL = 5,
      NEW = 6,
      WITH = 7,
      SUPER = 8,
      CASE = 9,
      VAL = 10,
      ABSTRACT = 11,
      FINAL = 12,
      PRIVATE = 13,
      PROTECTED = 14,
      OVERRIDE = 15,
      IMPLICIT = 16,
      VAR = 17,
      DEF = 18,
      TYPE = 19,
      EXTENDS = 20,
      TRUE = 21,
      FALSE = 22,
      OBJECT = 23,
      CLASS = 24,
      IMPORT = 25,
      PACKAGE = 26,
      YIELD = 27,
      DO = 28,
      TRAIT = 29,
      SEALED = 30,
      THROW = 31,
      TRY = 32,
      CATCH = 33,
      FINALLY = 34,
      WHILE = 35,
      RETURN = 36,
      MATCH = 37,
      FORSOME = 38,
      LAZY = 39,
      RW_UNDERSCORE = 40,
      RW_COLON = 41,
      RW_ASSIGNMENT = 42,
      RW_ROCKET = 43,
      RW_IN = 44,
      RW_UPPERBOUND = 45,
      RW_VIEWBOUND = 46,
      RW_LOWERBOUND = 47,
      RW_POUND = 48,
      RW_AT = 49,
      EOF_TOKEN = 50,
      SlComment = 51,
      MlComment = 52,
      DocComment = 53,
      IDENTIFIER = 54,
      IntegerLiteral = 55,
      FloatingPointLiteral = 56,
      DoubleLiteral = 57,
      CharacterLiteral = 58,
      StringLiteral = 59,
      SymbolLiteral = 60,
      LPAREN = 61,
      RPAREN = 62,
      LBRACE = 63,
      RBRACE = 64,
      LBRACKET = 65,
      RBRACKET = 66,
      SEMICOLON = 67,
      COLON = 68,
      COMMA = 69,
      DOT = 70;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "IF",
                 "FOR",
                 "ELSE",
                 "THIS",
                 "NULL",
                 "NEW",
                 "WITH",
                 "SUPER",
                 "CASE",
                 "VAL",
                 "ABSTRACT",
                 "FINAL",
                 "PRIVATE",
                 "PROTECTED",
                 "OVERRIDE",
                 "IMPLICIT",
                 "VAR",
                 "DEF",
                 "TYPE",
                 "EXTENDS",
                 "TRUE",
                 "FALSE",
                 "OBJECT",
                 "CLASS",
                 "IMPORT",
                 "PACKAGE",
                 "YIELD",
                 "DO",
                 "TRAIT",
                 "SEALED",
                 "THROW",
                 "TRY",
                 "CATCH",
                 "FINALLY",
                 "WHILE",
                 "RETURN",
                 "MATCH",
                 "FORSOME",
                 "LAZY",
                 "RW_UNDERSCORE",
                 "RW_COLON",
                 "RW_ASSIGNMENT",
                 "RW_ROCKET",
                 "RW_IN",
                 "RW_UPPERBOUND",
                 "RW_VIEWBOUND",
                 "RW_LOWERBOUND",
                 "RW_POUND",
                 "RW_AT",
                 "EOF_TOKEN",
                 "SlComment",
                 "MlComment",
                 "DocComment",
                 "IDENTIFIER",
                 "IntegerLiteral",
                 "FloatingPointLiteral",
                 "DoubleLiteral",
                 "CharacterLiteral",
                 "StringLiteral",
                 "SymbolLiteral",
                 "LPAREN",
                 "RPAREN",
                 "LBRACE",
                 "RBRACE",
                 "LBRACKET",
                 "RBRACKET",
                 "SEMICOLON",
                 "COLON",
                 "COMMA",
                 "DOT"
             };


    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = false;
}
